{{- if and .Values.namespace.create .Values.concierge.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "pinniped.componentNamespace" (dict "root" . "component" "concierge") }}
  labels:
{{ include "pinniped.standardLabels" . | indent 4 }}
{{- with .Values.commonLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- if and .Values.namespace.create .Values.supervisor.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "pinniped.componentNamespace" (dict "root" . "component" "supervisor") }}
  labels:
{{ include "pinniped.standardLabels" . | indent 4 }}
{{- with .Values.commonLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}