{{- if .Values.concierge.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pinniped.concierge.serviceAccountName" (dict "root" . "suffix" "") }}
  namespace: {{ include "pinniped.componentNamespace" (dict "root" . "component" "concierge") }}
  labels:
{{ include "pinniped.componentLabels" (dict "root" . "component" "concierge" "componentValues" .Values.concierge) | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pinniped.concierge.serviceAccountName" (dict "root" . "suffix" "kube-cert-agent") }}
  namespace: {{ include "pinniped.componentNamespace" (dict "root" . "component" "concierge") }}
  labels:
{{ include "pinniped.componentLabels" (dict "root" . "component" "concierge" "componentValues" .Values.concierge) | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pinniped.concierge.serviceAccountName" (dict "root" . "suffix" "impersonation-proxy") }}
  namespace: {{ include "pinniped.componentNamespace" (dict "root" . "component" "concierge") }}
  labels:
{{ include "pinniped.componentLabels" (dict "root" . "component" "concierge" "componentValues" .Values.concierge) | indent 4 }}
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
secrets: []
automountServiceAccountToken: false
{{- end }}
