{{- if and .Values.supervisor.enabled .Values.supervisor.ingress.enabled (eq .Values.supervisor.ingress.provider "gateway-api") .Values.supervisor.ingress.gatewayAPI.enabled }}
apiVersion: {{ .Values.supervisor.ingress.gatewayAPI.apiVersion }}
kind: {{ .Values.supervisor.ingress.gatewayAPI.routeKind }}
metadata:
  name: {{ default (printf "%s-gateway-route" (include "pinniped.componentName" (dict "root" . "component" "supervisor"))) .Values.supervisor.ingress.gatewayAPI.routeName | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "pinniped.componentNamespace" (dict "root" . "component" "supervisor") }}
  labels:
{{ include "pinniped.componentLabels" (dict "root" . "component" "supervisor" "componentValues" .Values.supervisor) | indent 4 }}
{{- with .Values.supervisor.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  parentRefs:
{{- if .Values.supervisor.ingress.gatewayAPI.parentRefs }}
{{ toYaml .Values.supervisor.ingress.gatewayAPI.parentRefs | indent 4 }}
{{- else }}
    []
{{- end }}
{{- if eq .Values.supervisor.ingress.gatewayAPI.routeKind "TLSRoute" }}
{{- $hostnames := .Values.supervisor.ingress.gatewayAPI.hostnames }}
{{- if and (eq (len $hostnames) 0) .Values.supervisor.ingress.hostname }}
  hostnames:
    - {{ .Values.supervisor.ingress.hostname | quote }}
{{- else if gt (len $hostnames) 0 }}
  hostnames:
{{ toYaml $hostnames | indent 4 }}
{{- end }}
{{- end }}
  rules:
    - backendRefs:
        - name: {{ include "pinniped.supervisor.exposureServiceName" . }}
          port: {{ .Values.supervisor.ingress.service.port }}
{{- end }}
