{{- if .Values.supervisor.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pinniped.supervisor.serviceAccountName" (dict "root" .) }}
  namespace: {{ include "pinniped.componentNamespace" (dict "root" . "component" "supervisor") }}
  labels:
{{ include "pinniped.componentLabels" (dict "root" . "component" "supervisor" "componentValues" .Values.supervisor) | indent 4 }}
{{- end }}
